### ISSUE TITLE
Expose Baffles Dashboard through a Kubernetes Service

### ISSUE THREAD

**Issue by andrewsgreene** [defenseunicorns/baffles-dashboard#2]
Given Baffles dashboard deployed to a kubernetes cluster
When navigating to [baffles.dev](baffles.dev)
Then a Kubernetes service exposes the dashboard
And baffles dashboard loads in the browser

**Comment by TheFutonEng** [comment]
Updating the GCP cluster with the latest consolidated zarf package that is in the baffles-matlab-demo repo.  Will take a look at ingress options next.

**Comment by TheFutonEng** [comment]
Applied the below ingress object to the cluster.  The K3s cluster was installed using Traefik so using that as the ingress controller.  

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: baffles-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zarf-baffles-api
            port: 
              number: 80

```

Needed to update the TF to open 80/443.  Getting a 404 currently while hitting one of the node addresses.  Progress but need to keep digging.

**Comment by TheFutonEng** [comment]
Traefik was installed as the ingress controller for this cluster.  For the demo, it has been decided that Istio will be the path forward since Bigbang is in play.  However, it was pretty easy to get a certificate/key in place with traefik.  Created a K8s tls secret:

```
[rmengert@oakridge:~/certs/config/live/airgap.store]
$ kubectl create secret tls -n baffles-api airgap.store --key privkey.pem --cert cert.pem 
secret/airgap.store created
[rmengert@oakridge:~/certs/config/live/airgap.store]
$
```

Then applied a traefik ingress route which is a different object compared to regular ingress:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: baffles-traefik
  namespace: baffles-api
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`airgap.store`)
    services:
    - name: zarf-baffles-api
      port: 80
  tls:
    secretName: airgap.store
```
